Set some advice/standards for test linting
yldio/standards pull request #5
Opened 2016-11-21 17:12 UTC by JGAntunes

What I am suggesting:

- [x] Gets out of the way;
- [x] Is not restricting;
- [x] Is safe, production ready, and project members have experience with it;
- [x] Promotes good coding practices.

^ Only used these because they're on the template but I'm not entirely sure if this applies to this specific PR. Anyway the point is giving some advice on using airbnb linting rules when linting tests, as it won't run straight out of the box for the tools we're used to (mocha, chai, etc.).

2016-11-21 18:07 UTC, nfcampos commented
i'd strongly suggest staying away from mocha as a test runner but i guess enough projects use it that it's useful to have rules specifically for it?

2016-11-21 18:40 UTC, JGAntunes commented
This is not about mocha but more about a specific set of rules you'll
probably need to lint your tests. Mocha was just an example.

On 21 Nov 2016 6:07 p.m., "Nuno Campos" <notifications@github.com> wrote:

> i'd strongly suggest staying away from mocha as a test runner but i guess
> enough projects use it that it's useful to have rules specifically for it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yldio/standards/pull/5#issuecomment-262018701>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AFh8fz0V1bxBbMQ0j-oITybQZJYwT3Ilks5rAd3igaJpZM4K4dXq>
> .
>

2016-11-21 20:03 UTC, nfcampos commented
yes but mocha is the only test runner that uses this for setting timeout...

2016-11-21 20:07 UTC, nfcampos commented
i guess what i mean is that rules that apply only for certain dependencies should be more explicitly worded to reflect that, eg. something like "If you use chai then disable no-unused-expressions"

2016-11-22 11:00 UTC, tomgco requested changes
A few things that I personally disagree with here. (Changing lint specifically for tests)

2016-11-22 11:00 UTC, tomgco commented on js-code-style.md
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
I disagree with this, having consistency between our code and tests is paramount.

2016-11-22 11:00 UTC, tomgco commented on js-code-style.md
> +  * `func-names`: Taking into account the above, it is just painful to name all of your test functions
See Above ^^

2016-11-22 11:00 UTC, tomgco commented on js-code-style.md
> +### For tests
Maybe something about setting the correct `NODE_ENV` as an explicit step?

2016-11-22 11:00 UTC, tomgco commented on js-code-style.md
> +### For tests
I really think that having a standard test output format (TAP) is much better than a custom reporter. This allows anyone to format test output as the developer wishes.

2016-11-22 14:24 UTC, JGAntunes commented
I spoke with @nfcampos yesterday and I agree that maybe we should either drop this or probably rephrase it to something more of a -  "Rules/configuration steps to watch out when using mocha/jest/lab/tape/ava/<fancy-test-runner>".

2016-11-22 14:30 UTC, JGAntunes commented on js-code-style.md
> +### For tests
Agree with all of it. But should this be in the JS Code Style?

2016-11-22 14:51 UTC, JGAntunes commented on js-code-style.md
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
For me is just a matter of people that use test runners such as mocha (not sure if anymore suffer from the same problems) to be aware of the set backs of using arrow functions. If everyone is one board with it I'm okay too :+1:
Also, the context of this whole discussion should probably change I think - see https://github.com/yldio/standards/pull/5#issuecomment-262253587

2016-11-22 14:53 UTC, JGAntunes commented on js-code-style.md
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
Although I tend to disagree with this specific rule in some scenarios, for which I think it might fail, but that will be a problem for another discussion :smile:

2016-11-22 14:54 UTC, joaojeronimo commented on js-code-style.md
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
If this illustrates that mocha is not a good choice of a test runner even better, I hope we can set a standard test runner that everyone agrees will play well with linters and other tools.

2016-11-22 15:08 UTC, JGAntunes commented
@joaojeronimo I feel like that's too much of an Utopian dream :smile:

João Antunes

On 22 November 2016 at 14:54, João Jerónimo <notifications@github.com>
wrote:

> *@joaojeronimo* commented on this pull request.
> ------------------------------
>
> In js-code-style.md <https://github.com/yldio/standards/pull/5>:
>
> >
>  We can start a project to extend one of those bases if we find we have issues with some rules.
>
> +### For tests
> +
> +You should fine-tune the config for your tests folder.
> +First set the right environment in your eslint config (`mocha` for example).
> +There's also a set of rules that you should probably ignore/change. Consider the following:
> +
> +  * `no-unused-expressions`: Should be `off` when using assertion libs like `chai` for example.
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
>
> If this illustrates that mocha is not a good choice of a test runner even
> better, I hope we can set a standard test runner that everyone agrees will
> play well with linters and other tools.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yldio/standards/pull/5>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFh8fzen49EfYjpOYyBBN7JIQ9GRk99Pks5rAwIPgaJpZM4K4dXq>
> .
>

2016-11-22 15:08 UTC, JGAntunes commented on js-code-style.md
> +  * `prefer-arrow-callback`: Should be `off` when using test frameworks like mocha as stated [in their documentation](https://mochajs.org/#arrow-functions).
@joaojeronimo I feel like that's too much of an Utopian dream :smile:

2016-12-05 10:16 UTC, joaojeronimo commented
So what's the status of this ?

2016-12-05 10:39 UTC, JGAntunes commented
I'll rephrase some of the stuff here, to change from "mandatory", to advisory when using stuff like mocha or chai, etc. is that ok? Or I can also close this, since it may not be considered much of a standard but more of a set of advice on how to deal with the airbnb eslint config.

2016-12-05 11:12 UTC, joaojeronimo commented
Choose one and

![](http://i.giphy.com/10FUfTApAeoZK8.gif)

2016-12-06 17:39 UTC, tomgco approved these changes

2016-12-06 17:40 UTC, tomgco commented
Didn't realise the review was blocking merges. I am happy, sorry 💃 🗡

2016-12-07 15:35 UTC, merged